import { StyleSheet } from 'react-native';

export const palette = {
  background: '#0f172a',
  card: '#111827',
  muted: '#94a3b8',
  primary: '#38bdf8',
  primaryStrong: '#0ea5e9',
  secondary: '#1f2937',
  accent: '#f59e0b',
  success: '#22c55e',
  error: '#ef4444',
  white: '#f8fafc',
  darkText: '#0f172a',
  greenDark: '#2d5016',
  grayText: '#4a4a4a',
  orange: '#e8883a',
};

// Estilos otimizados para TABLET
const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  scrollContent: {
    padding: 40,
    paddingBottom: 60,
    paddingLeft: 40,
    paddingRight: 40,
    minHeight: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  card: {
    backgroundColor: palette.card,
    borderRadius: 20,
    padding: 32,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.08)',
  },
  cardTitle: {
    color: '#064E4C',
    fontSize: 32,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginBottom: 16,
    textAlign: 'center',
  },
  muted: {
    color: '#064E4C',
    fontSize: 20,
    lineHeight: 28,
  },
  highlight: {
    color: palette.white,
    fontWeight: '700',
  },
  label: {
    color: palette.muted,
    fontSize: 20,
    marginTop: 24,
    marginBottom: 10,
  },
  input: {
    borderWidth: 2,
    borderColor: '#334155',
    borderRadius: 16,
    paddingVertical: 18,
    paddingHorizontal: 20,
    color: palette.white,
    backgroundColor: '#0b1220',
    fontSize: 22,
  },
  buttonRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 20,
    marginTop: 28,
  },
  buttonColumn: {
    gap: 16,
    marginTop: 24,
  },
  primaryButton: {
    backgroundColor: palette.primary,
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 32,
    minWidth: 300,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: palette.darkText,
    fontWeight: '600',
    fontSize: 22,
  },
  secondaryButton: {
    backgroundColor: palette.secondary,
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 32,
    minWidth: 300,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#334155',
  },
  secondaryButtonText: {
    color: palette.white,
    fontWeight: '600',
    fontSize: 22,
  },
  linkButtonText: {
    color: palette.greenDark,
    textDecorationLine: 'underline',
    fontWeight: '600',
    fontSize: 20,
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  status: {
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
  },
  statusText: {
    color: palette.white,
    textAlign: 'center',
    fontSize: 20,
  },
  faturaScroll: {
    marginTop: 24,
    width: '100%',
  },
  faturaHeader: {
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#0b5967',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 16,
    width: '96%',
    alignSelf: 'center',
  },
  faturaHeaderText: {
    color: '#D6DAC0',
    fontWeight: '700',
    fontSize: 18,
    flex: 1,
    textAlign: 'center',
  },
  faturaRow: {
    width: '96%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#0a4a52',
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginTop: 10,
    alignSelf: 'center',
  },
  faturaRowSelected: {
    backgroundColor: 'rgba(56,189,248,0.15)',
  },
  faturaRowText: {
    flex: 1,
    color: palette.white,
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  faturaRowValue: {
    flex: 1,
    color: palette.white,
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  rowActionButton: {
    flex: 1,
    backgroundColor: '#d3d94a',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  rowActionButtonText: {
    color: '#0b4a56',
    fontWeight: '800',
    fontSize: 16,
  },
  actionsContainer: {
    marginTop: 24,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: 'rgba(56,189,248,0.35)',
    padding: 24,
    backgroundColor: 'rgba(8,17,31,0.9)',
  },
  actionsTitle: {
    color: palette.white,
    fontWeight: '600',
    textAlign: 'center',
    fontSize: 22,
  },
  actionsGrid: {
    marginTop: 20,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    justifyContent: 'center',
  },
  actionButton: {
    flexBasis: '48%',
    minWidth: 200,
    backgroundColor: 'rgba(15,23,42,0.85)',
    borderWidth: 2,
    borderColor: 'rgba(56,189,248,0.3)',
    borderRadius: 14,
    paddingVertical: 18,
    alignItems: 'center',
  },
  actionButtonDisabled: {
    opacity: 0.5,
  },
  actionButtonText: {
    color: palette.white,
    fontWeight: '600',
    fontSize: 20,
  },
  loading: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 16,
  },
  loadingText: {
    color: palette.muted,
    fontSize: 20,
  },
  // Estilos da tela de boas-vindas (CPF) - TABLET
  welcomeCard: {
    backgroundColor: 'transparent',
    paddingVertical: 40,
    paddingHorizontal: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  welcomeTitle: {
    color: palette.greenDark,
    fontSize: 48,
    fontWeight: '800',
    letterSpacing: 2,
    textAlign: 'center',
    marginBottom: 32,
    textTransform: 'uppercase',
  },
  welcomeSubtitle: {
    color: palette.grayText,
    fontSize: 32,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 8,
  },
  welcomeDescription: {
    color: palette.grayText,
    fontSize: 26,
    fontWeight: '400',
    textAlign: 'center',
    marginBottom: 40,
  },
  hiddenInput: {
    position: 'absolute',
    opacity: 0,
    height: 0,
    width: 0,
  },
  orangeButton: {
    backgroundColor: palette.orange,
    borderRadius: 40,
    paddingVertical: 24,
    paddingHorizontal: 64,
    minWidth: 380,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 8,
  },
  orangeButtonText: {
    color: palette.white,
    fontWeight: '700',
    fontSize: 26,
    letterSpacing: 1,
  },
  cpfInputContainer: {
    width: '100%',
    alignItems: 'center',
    gap: 32,
  },
  cpfInput: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderWidth: 3,
    borderColor: palette.greenDark,
    borderRadius: 20,
    paddingVertical: 22,
    paddingHorizontal: 32,
    fontSize: 36,
    fontWeight: '600',
    color: palette.grayText,
    textAlign: 'center',
    minWidth: 400,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  cpfButtonRow: {
    flexDirection: 'row',
    gap: 24,
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  cancelButton: {
    backgroundColor: 'transparent',
    borderWidth: 3,
    borderColor: palette.grayText,
    borderRadius: 40,
    paddingVertical: 22,
    paddingHorizontal: 48,
    alignItems: 'center',
  },
  cancelButtonText: {
    color: palette.grayText,
    fontWeight: '600',
    fontSize: 22,
  },
  // Estilos para tela PJ - TABLET
  pjTitle: {
    color: palette.greenDark,
    fontSize: 42,
    fontWeight: '700',
    fontStyle: 'italic',
    textAlign: 'center',
    marginBottom: 20,
  },
  pjBadge: {
    backgroundColor: palette.greenDark,
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 32,
    marginBottom: 40,
  },
  pjBadgeText: {
    color: palette.white,
    fontSize: 26,
    fontWeight: '700',
    letterSpacing: 2,
  },
  pfBadge: {
    backgroundColor: palette.primary,
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 32,
    marginBottom: 40,
  },
  pfBadgeText: {
    color: palette.white,
    fontSize: 26,
    fontWeight: '700',
    letterSpacing: 2,
  },
  pjWelcome: {
    color: palette.greenDark,
    fontSize: 36,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 24,
  },
  pjNextStep: {
    color: palette.grayText,
    fontSize: 26,
    fontStyle: 'italic',
    textAlign: 'center',
    marginBottom: 32,
  },
  greenButton: {
    backgroundColor: palette.greenDark,
    borderRadius: 40,
    paddingVertical: 24,
    paddingHorizontal: 48,
    minWidth: 400,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 8,
  },
  greenButtonText: {
    color: palette.white,
    fontWeight: '700',
    fontSize: 24,
    letterSpacing: 1,
  },
  faturaScreenContainer: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    paddingHorizontal: 0,
    paddingVertical: 0,
    marginTop: 12,
    shadowColor: 'transparent',
    alignItems: 'center',
  },
  semFaturaContainer: {
    marginTop: 20,
    alignItems: 'center',
    gap: 16,
  },
  semFaturaTexto: {
    color: '#064E4C',
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  // Estilos do formulário - TABLET
  formContainer: {
    width: '100%',
    paddingHorizontal: 32,
    marginBottom: 32,
  },
  formLabel: {
    color: palette.greenDark,
    fontSize: 20,
    fontWeight: '600',
    marginTop: 24,
    marginBottom: 12,
  },
  formInput: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderWidth: 3,
    borderColor: palette.greenDark,
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 24,
    fontSize: 26,
    fontWeight: '500',
    color: palette.grayText,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  // Estilos de layout/imagens
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  topLeftImage: {
    position: 'absolute',
    top: 0,
    left: '10%',
    width: '25%',
    height: 150,
    zIndex: 2,
  },
  topRightImage: {
    position: 'absolute',
    top: 0,
    right: '-4%',
    width: '25%',
    height: 150,
    zIndex: 2,
  },
  bottomLeftImage: {
    position: 'absolute',
    bottom: 0,
    right: '66%',
    width: '42%',
    height: '62%',
    zIndex: 1,
  },
  bottomRightImage: {
    position: 'absolute',
    bottom: '3%',
    right: '-15.2%',
    width: '40%',
    height: '65%',
    zIndex: 2,
  },
  atendenteContainer: {
    position: 'absolute',
    bottom: '-2%',
    left: 0,
    zIndex: 1,
  },
  atendenteImage: {
    zIndex: 1,
  },
});

export default styles;
